image:
  repository: altran1502/supabase-server
  pullPolicy: IfNotPresent
  tag: v1.106.4

mlImage:
  repository: altran1502/supabase-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.106.4

mlCudaImage:
  repository: altran1502/supabase-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.106.4-cuda

mlOpenvinoImage:
  repository: altran1502/supabase-machine-learning
  pullPolicy: IfNotPresent
  tag: v1.106.4-openvino

pgvectorImage:
  repository: tensorchord/pgvecto-rs
  pullPolicy: IfNotPresent
  tag: pg15-v0.2.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

supabaseGPU: {}

supabaseConfig:
  publicLoginMessage: ''
  enableML: true
  mlImageType: mlImage
  logLevel: log
  huggingFaceEndpoint: ''

supabaseNetwork:
  webuiPort: 30041
  # Not user configurable, will be hidden on UI
  # Putting it here in case it needs to be configurable
  # in the future.
  machinelearningPort: 32002

supabaseStorage:
  uploads:
    type: ixVolume
    ixVolumeConfig:
      datasetName: uploads
  library:
    type: ixVolume
    ixVolumeConfig:
      datasetName: library
  thumbs:
    type: ixVolume
    ixVolumeConfig:
      datasetName: thumbs
  profile:
    type: ixVolume
    ixVolumeConfig:
      datasetName: profile
  video:
    type: ixVolume
    ixVolumeConfig:
      datasetName: video
  additionalLibraries: []
  pgData:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgData
  pgBackup:
    type: ixVolume
    ixVolumeConfig:
      datasetName: pgBackup

notes:
  custom: |
    ## Database
    You can connect to the database using the pgAdmin App from the catalog

    <details>
      <summary>Database Details</summary>

      - Database: `supabase`
      - Username: `supabase`
      - Password: `{{ .Values.supabaseDbPass }}`
      - Host:     `{{ .Values.supabaseDbHost }}.{{ .Release.Namespace }}.svc.cluster.local`
      - Port:     `5432`

    </details>
    {{- $_ := unset .Values "supabaseDbPass" }}
    {{- $_ := unset .Values "supabaseDbHost" }}